# Generated by Django 3.1 on 2020-08-22 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='dispatch_name',
            new_name='transpoter_name',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='docketno',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatch',
            name='invoice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop_site.invoice'),
            preserve_default=False,
        ),
    ]
