# Generated by Django 3.1 on 2020-08-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0003_auto_20200822_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
    ]
